AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::hello-spring-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  HelloSpringLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.weather.data.WeatherLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: ./target/data-0.0.1-SNAPSHOT.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  HelloSpringLambdaApi:
    Description: URL for application
    
    Export:
      Name: HelloSpringLambdaApi
